###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/626747bb406bd49c040fa2b1
###
GET http://localhost:8080/contacts/626747bb406bd49c040fa2b2
###
GET http://localhost:8080/contacts/626747bb406bd49c040fa2b3

### Create new contact
POST http://localhost:8080/contacts
content-type: application/json

{
    "firstName":"Rubeus",
    "lastName":"Hagrid",
    "email":"rubeusHagrid@hps.com",
    "favoriteColor":"I don't know",
    "birthday":"12/06/28"
}

###
PUT http://localhost:8080/contacts/626747bb406bd49c040fa2b1
Content-Type: application/json

{
    "firstName":"Harry",
    "lastName":"Potter",
    "email":"harryPotterSecondEmail@hps.com",
    "favoriteColor":"I don't know",
    "birthday":"01/01/80"
}

###
DELETE http://localhost:8080/contacts/626747bb406bd49c040fa2b1





// Production
###
GET https://cse341-node-api.herokuapp.com/contacts
###
GET https://cse341-node-api.herokuapp.com/contacts/626747bb406bd49c040fa2b1
###
GET https://cse341-node-api.herokuapp.com/contacts/626747bb406bd49c040fa2b2
###
GET https://cse341-node-api.herokuapp.com/contacts/626747bb406bd49c040fa2b3